title:              Tanned-Bear's Blog
email:              k2hyun4@naver.com
description:        
author:             k2hyun4
baseurl:            "/"
url:                "https://k2hyun4.github.io"

# Social Profiles
twitter_username:   
github_username:    k2hyun4
facebook_username:  k2hyun4
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
